### ISSUE TITLE
Would it be possible to declare device_class for liveboxtvuhd

### ISSUE THREAD

**Issue by Arkhelion** [AkA57/liveboxtvuhd#23]
Hi,

Would it be possible to declare device_class: tv for the media_player entities created with liveboxtvuhd?
This could lead to a better behaviour with the stock homebridge integration (hypothetically).

**Comment by AkA57** [comment]
Hi,

From what I see it is possible to do it directly on your configuration.yaml file.
For example, I ha the following media_player
```
media_player
  - platform: liveboxtvuhd
    name: Livebox
    host: 172.17.31.2
    port: 8080
    scan_interval: 10
```

And I can customized it to a TV device
```
homeassistant:
  customize:
    media_player.liveboxtvuhd:
      device_class: tv
```

Then you should add it to your homekit configuration

```
. . .
  include_entities:
    - media_player.liveboxtvuhd
entity_config:
  media_player.liveboxtvuhd:
    name: "Livebox"
    feature_list:
      - feature: on_off
      - feature: play_pause
      - feature: play_stop
      - feature: toggle_mute
```
