### ISSUE TITLE
Remote entity not created

### ISSUE THREAD

**Issue by PhoenixR49** [AkA57/liveboxtvuhd#47]
First of all, many thanks for your integration, it's great!

I'm having a problem creating the remote entity for the decoder. Here's the configuration I currently have: 
```yaml
# Media players
media_player:
  - platform: liveboxtvuhd
    name: Décodeur TV UHD
    host: 192.168.1.17
    port: 8080
    scan_interval: 5

# Remotes
remote:
  - platform: liveboxtvuhd
    name: Décodeur TV UHD
    host: 192.168.1.17
    port: 8080
    scan_interval: 30
```

When I go to the tab to restart Home Assistant, an error appears: "Platform error 'remote' from integration 'liveboxtvuhd' - Platform liveboxtvuhd.remote not found". After restart, no remote entity is created...

I've tried to reproduce the bug on a test Home Assistant installation and the problem disappears and the remote entity is created.

Would you know how to do this?
