### ISSUE TITLE
Two boxes possible ?

### ISSUE THREAD

**Issue by Nico4xo** [AkA57/liveboxtvuhd#55]
Hello, and thank you for this HACS.

I use two Orange UHD TV boxes at home.
I tried adding the second one to the configuration file by copying and pasting the original code and changing the IP address, but without success.
Is there a way to make this program manage both?

Thank you in advance for your reply.

Nico

**Comment by AkA57** [comment]
Hello, 
Did you try with 2 differents name ?

```
media_player:
  - platform: liveboxtvuhd
    name: livebox-salon
    host: 192.168.1.2
    port: 8080
    scan_interval: 30
    country: france
  - platform: liveboxtvuhd
    name: livebox-chambre
    host: 192.168.1.3
    port: 8080
    scan_interval: 30
    country: france
```

![Image](https://github.com/user-attachments/assets/66cddb77-e9c1-4df0-8a8b-c65cce04c587)
